
# Update this line if your project id is different
project_id = "jcoizqugqeekhpniucra"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions.send-sms-alert]
verify_jwt = false

[storage]
enabled = true
