// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcoizqugqeekhpniucra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impjb2l6cXVncWVla2hwbml1Y3JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NTgwMTUsImV4cCI6MjA2MDUzNDAxNX0.W9oaXF5UF6rVxGm4AK7Hw2aT0bGM9PaGPUMCEplRzSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);